### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
See: https://github.com/gradle/wrapper-validation-action

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Out of curiosity, why?

**Comment by npryce** [comment]
Oops. I swapped the branches around and deleted the master branch. That must have closed PRS.

**Comment by npryce** [comment]
Applied manually to the `jvm` branch

**Comment by JLLeitschuh** [comment]
If you're using Gradle on all of your code on all branches, may be good to put it on all of them?

**Pull request closed without merging**
