### PR TITLE
Add sugar for any.shouldMatch

### PR DESCRIPTION
**Pull request by dmcg**
Looks like this give readability and composability

### CODE REVIEW

**Comment by dmcg** [comment]
I take it by your lack of a rename that you didn't find anything better! shouldBe works for some, and shouldMatch for others. You can 

`import com.natpryce.hamkrest.should.shouldMatch as shouldBe`

and use `(84 / 2) shouldBe equalTo(42)` when it suits.

I'm just so happy to be able to have reified generics that goddamn it I'm going to have them reified if they can be ;-)

**Comment by dmcg** [comment]
BTW - the readme still uses the non-operator style

**Comment by npryce** [comment]
The best I could come up with is "satisfies", which is awkward for
everything.

**Comment by npryce** [comment]
How about one of...

```
actual definitely isWithin(10..20)
```

or

```
actual now isWithin(10..20)
```

or (for people who like Cucumber)

```
actual then isWithin(10..20)
```

or (for when you need to be very definite)

```
actual effing isWithin(10..20)
```

**Pull request merged**
